# This file stores the flash_commands for each mcus
# Previous version KCONFIG_CONFIG was needed now it is automaticly added when make flash is called
# version : 0.1
# tested/supported flash methods :
#  - make flash
#  - sdcard_flash
#  - flashtool.py
#  - mount/cp/umount (for rp2040)
 
#[rpi]
#klipper_section: mcu rpi
#action_command: make flash

#[octopus]
#klipper_section: mcu
#action_command: ~/klipper/scripts/flash-sdcard.sh /dev/ttyAMA0 btt-octopus-f446-v1

#[mcu]
#quiet_command: enter_bootloader -u <YOUR_CANBUS_UUID>
#action_command: ~/klippy-env/bin/python3 ~/katapult/scripts/flashtool.py -d /dev/serial/by-id/usb-katapult_stm32f446xx_<BOARD_ID>-if00

[RaspberryPi]
klipper_section: mcu rpi
action_command: make flash

[leviathan]
klipper_section: mcu
# catalyst on usb-serial port (using bootloader_usb.py)
action_command: ~/klippy-env/bin/python3 ~/ukam/bootloader_usb.py /dev/serial/by-id/usb-Klipper_stm32f446xx_3C0034000A51313133353932-if00
quiet_command: sleep 1
action_command: ~/klippy-env/bin/python3 ~/katapult/scripts/flashtool.py -d /dev/serial/by-id/usb-katapult_stm32f446xx_3C0034000A51313133353932-if00

[nhk36]
klipper_section: mcu
# catalyst on usb-serial port (using bootloader_usb.py)
action_command: ~/klippy-env/bin/python3 ~/ukam/bootloader_usb.py /dev/serial/by-id/usb-Klipper_rp2040_4D4A393336137FFC-if00
quiet_command: sleep 1
action_command: ~/klippy-env/bin/python3 ~/katapult/scripts/flashtool.py -d /dev/serial/by-id/usb-katapult_rp2040_4D4A393336137FFC-if00
